name: run-tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      with:
        node-version: '16.x'
      - name: Install modules
        run: npm ci
      - name: Run tests
        run: npm tests
